CREATE TABLE wikis {
    wikis_id BIGINT NOT NULL AUTO_INCREMENT,
    topic VARCHAR(99) NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (wikis_id)
};